Repository elastic/elastic-agent-changelog-tool, pull requests merged in 2022-11, with the labels that each got.

#122 ci: docker login
  .ci/Jenkinsfile
Labels: Team:Automation, skip-changelog

#123 release: provide docker images
  .ci/Jenkinsfile
  .goreleaser.yml
  Dockerfile
Labels: ci, skip-changelog

#126 provide docs for GitHub auth
  docs/github-authentication.md
  docs/usage.md
Labels: skip-changelog

#125 Document new URL format for PR and issue IDs
  docs/getting-started.md
  docs/release-process.md
  internal/changelog/fragment/creator_internal_test.go
  internal/changelog/fragment/template.yaml
Labels: skip-changelog
